version: "3.9"
services:
  dev:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5678:5678"
      - "9229:9229"
    volumes:
      - .:/home/node/app
    command: ["npm", "run", "dev"]
